### ISSUE TITLE
ask a question 

### ISSUE THREAD

**Issue by HKCaesar** [nmhkahn/DNCNN-tensorflow#1]
Dear Sir,
    I have srtup my own dataset,but ,the program does not work! Could you please give a simple dataset or more structure details?
   
Thanks!

**Comment by nmhkahn** [comment]
Hi,
Sorry, but I accidentally deleted my dataset :( 
Instead, could you tell me details about your settings? 
Such as directory structure, csv example, and error messages etc..

**Comment by HKCaesar** [comment]
what does the dataset - val mean? sets of the denoised train dataset(Ground truth for train ) ?

**Comment by nmhkahn** [comment]
`val` means validation sets. This dataset is for finding best hyperparameters before test models. But if you don't want to do hyperparameter tuning, just ignore about validation sets. In that case, just prepare only`train` and `test` dataset will be enough.

**Comment by HKCaesar** [comment]
![image](https://user-images.githubusercontent.com/9332975/27735839-1aa190f2-5dd4-11e7-9745-cbc6c509bd7f.png)
CSV:
test001.jpg,/workspace/dl/keras/tensorflow/DNCNN-tensorflow-slim/dataset/train/test001.jpg
test002.jpg,/workspace/dl/keras/tensorflow/DNCNN-tensorflow-slim/dataset/train/test002.jpg
test003.jpg,/workspace/dl/keras/tensorflow/DNCNN-tensorflow-slim/dataset/train/test003.jpg

*.jpg just some noised picture 
![image](https://user-images.githubusercontent.com/9332975/27735919-74cef114-5dd4-11e7-945b-6d3f7a766f57.png)
should I prepare some denoised image to train?How?

**Comment by nmhkahn** [comment]
In the csv file 
```
reference_image_path,artifact_image_path
```
`reference_image` means literally a reference image which didn't noised at all. of course `artifact_image` means noised image that you already have.
So don't need denoised image, just prepare a reference and noised image.

**Comment by HKCaesar** [comment]
OK,I got it. Maybe,description of 
Datasets train.csv val.csv test.csv is not so clear! 
Then the structure of test.csv (reference_image_path,artifact_image_path) ?A location  for noised iamge, A location for denoised (result)image?

**Comment by nmhkahn** [comment]
In the structure of test.csv, `reference_image_path` means **original** image that didn't noised at all. And `artifact_image_path` is about **noised** image.
It because neural network get artifact images as an input and return denoised image. And it compare denoised result image and reference image(or original image) when training. So don't need to have denoised images in your dataset.

And I thought that just describe as val.csv is okay since val(or validataion) is usual keyword in machine learning area.
