### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by doantientai** [nmhkahn/DNCNN-tensorflow#2]
I got this error when I run evaluate.py

```
Traceback (most recent call last):
  File "dncnn/evaluate.py", line 166, in <module>
    main(config)
  File "dncnn/evaluate.py", line 161, in main
    loop(data_info, config)
  File "dncnn/evaluate.py", line 137, in loop
    artifact_path, reference_path, quality = info
ValueError: not enough values to unpack (expected 3, got 2)

```
In my .csv files, there are only 2 columns. If you unpack 3 values from `info`, I guess there should be the third column, right?

**Comment by nmhkahn** [comment]
Hi, 
I'm sorry but README files is incorrect, csv file has to be like

```
filename,filename,quality
...
```

Maybe when I made doc file, I forgot about quality score :( anyway this should be changed.
Thanks.

**Comment by doantientai** [comment]
Thank you a lot. But I'm still confused a bit, what should I put in column `quality`? What does it mean?

**Comment by nmhkahn** [comment]
Quality factor means image quality literally.

In many papers about image denoising or super-resolution, they always evaluate their model in each quality factor. It will be helpful if you see table 1, 2, 3 in [this paper](https://pdfs.semanticscholar.org/0964/2681d46282e76fd9d1336001ef6473b72ec8.pdf)

So anyway, I wanted to follow this approaches. 
But in case if you don't want, just record quality column with fix number like zero or something.

**Comment by doantientai** [comment]
Thank you! That's right. I was confused about which quality measurement to use. I guess I will just let it be zeros by now then I will compute the quality on the output images later.
